#! /usr/local/bin/python3

chaine_saisie = input("Saisissez un nombre")

nb = int(chaine_saisie)
print(" 1 *", nb, "=", 1 * nb)
print(" 2 *", nb, "=", 2 * nb)
print(" 3 *", nb, "=", 3 * nb)
print(" 4 *", nb, "=", 4 * nb)
print(" 5 *", nb, "=", 5 * nb)
print(" 6 *", nb, "=", 6 * nb)
print(" 7 *", nb, "=", 7 * nb)
print(" 8 *", nb, "=", 8 * nb)
print(" 9 *", nb, "=", 9 * nb)
print("10 *", nb, "=", 10 * nb)
print("11 *", nb, "=", 11 * nb)
print("12 *", nb, "=", 12 * nb)
print("13 *", nb, "=", 13 * nb)
print("14 *", nb, "=", 14 * nb)
print("15 *", nb, "=", 15 * nb)
print("16 *", nb, "=", 16 * nb)
print("17 *", nb, "=", 17 * nb)
print("18 *", nb, "=", 18 * nb)
print("19 *", nb, "=", 19 * nb)
print("20 *", nb, "=", 20 * nb)